# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/control_sub_nf_riffa_dma_1_0.xci
# IP: The module: 'control_sub_nf_riffa_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_fifo_2clk_32d_4u || ORIG_REF_NAME==axis_fifo_2clk_32d_4u}]

# XDC: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_fifo_2clk_32d_4u || ORIG_REF_NAME==axis_fifo_2clk_32d_4u}] {/U0 }]/U0 ]]

# XDC: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_fifo_2clk_32d_4u || ORIG_REF_NAME==axis_fifo_2clk_32d_4u}] {/U0 }]/U0 ]]

# XDC: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u_ooc.xdc

# IP: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/control_sub_nf_riffa_dma_1_0.xci
# IP: The module: 'control_sub_nf_riffa_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_fifo_2clk_32d_4u || ORIG_REF_NAME==axis_fifo_2clk_32d_4u}]

# XDC: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_fifo_2clk_32d_4u || ORIG_REF_NAME==axis_fifo_2clk_32d_4u}] {/U0 }]/U0 ]]

# XDC: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_fifo_2clk_32d_4u || ORIG_REF_NAME==axis_fifo_2clk_32d_4u}] {/U0 }]/U0 ]]

# XDC: /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u_ooc.xdc
