# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/maskerk/NetFPGA-SUME-live-master/lib/hw/std/constraints/generic_bit.xdc

# XDC: /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_general.xdc

# XDC: /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_10g.xdc

# IP: ip/output_port_lookup_ip/output_port_lookup_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==output_port_lookup_ip || ORIG_REF_NAME==output_port_lookup_ip}]
