# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.cache/wt [current_project]
set_property parent.project_path /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/ip_repo [current_project]
set_property ip_output_repo /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/create_ip/id_rom16x32.coe
read_verilog -library xil_defaultlib {
  /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/hdl/axi_clocking.v
  /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/hdl/nf_datapath.v
  /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/hdl/top.v
}
read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/output_port_lookup_ip/output_port_lookup_ip.xci
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/output_port_lookup_ip/output_port_lookup_ip.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/input_arbiter_ip/input_arbiter_ip.xci
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/input_arbiter_ip/input_arbiter_ip.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/output_queues_ip/output_queues_ip.xci
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/output_queues_ip/output_queues_ip.xci]

add_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/control_sub.bd
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_xbar_0/control_sub_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_dwidth_dma_tx_0/control_sub_axis_dwidth_dma_tx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_dwidth_dma_rx_0/control_sub_axis_dwidth_dma_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_fifo_10g_rx_0/control_sub_axis_fifo_10g_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_fifo_10g_rx_0/control_sub_axis_fifo_10g_rx_0/control_sub_axis_fifo_10g_rx_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_fifo_10g_rx_0/control_sub_axis_fifo_10g_rx_0/control_sub_axis_fifo_10g_rx_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_fifo_10g_tx_0/control_sub_axis_fifo_10g_tx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_fifo_10g_tx_0/control_sub_axis_fifo_10g_tx_0/control_sub_axis_fifo_10g_tx_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axis_fifo_10g_tx_0/control_sub_axis_fifo_10g_tx_0/control_sub_axis_fifo_10g_tx_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/ip_proj/nf_riffa_dma.srcs/sources_1/ip/axis_fifo_2clk_32d_4u/axis_fifo_2clk_32d_4u_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_clock_converter_0_0/control_sub_axi_clock_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_clock_converter_0_0/control_sub_axi_clock_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_pcie3_7x_1_0/source/control_sub_pcie3_7x_1_0-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_pcie3_7x_1_0/synth/control_sub_pcie3_7x_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_iic_0_0/control_sub_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_iic_0_0/control_sub_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_uartlite_0_0/control_sub_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_uartlite_0_0/control_sub_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_axi_uartlite_0_0/control_sub_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_clk_wiz_1_0/control_sub_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_clk_wiz_1_0/control_sub_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_clk_wiz_1_0/control_sub_clk_wiz_1_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_clk_wiz_1_0/control_sub_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_mdm_1_0/control_sub_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_mdm_1_0/control_sub_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_microblaze_0_0/control_sub_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_microblaze_0_0/control_sub_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_microblaze_0_0/control_sub_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_microblaze_0_axi_intc_0/control_sub_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_microblaze_0_axi_intc_0/control_sub_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_microblaze_0_axi_intc_0/control_sub_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_xbar_1/control_sub_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_bram_if_cntlr_0/control_sub_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_v10_0/control_sub_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_dlmb_v10_0/control_sub_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_ilmb_bram_if_cntlr_0/control_sub_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_ilmb_v10_0/control_sub_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_ilmb_v10_0/control_sub_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_lmb_bram_0/control_sub_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_rst_clk_wiz_1_100M_0/control_sub_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_rst_clk_wiz_1_100M_0/control_sub_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_rst_clk_wiz_1_100M_0/control_sub_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_s00_data_fifo_0/control_sub_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m00_data_fifo_0/control_sub_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m01_data_fifo_0/control_sub_m01_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m02_data_fifo_0/control_sub_m02_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m03_data_fifo_0/control_sub_m03_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m04_data_fifo_0/control_sub_m04_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m05_data_fifo_0/control_sub_m05_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m06_data_fifo_0/control_sub_m06_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m07_data_fifo_0/control_sub_m07_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_m08_data_fifo_0/control_sub_m08_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_auto_cc_0/control_sub_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/ip/control_sub_auto_cc_0/control_sub_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/control_sub_ooc.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/bd/control_sub/control_sub.bd]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/axi_10g_ethernet_nonshared.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_0/synth/bd_7ad4_xmac_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_0/synth/bd_7ad4_xmac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/synth/bd_7ad4_xpcs_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/synth/bd_7ad4_xpcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/synth/bd_7ad4_xpcs_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/bd_0/bd_7ad4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/synth/axi_10g_ethernet_nonshared_ooc.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_nonshared/axi_10g_ethernet_nonshared.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_status/fifo_generator_status.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_status/fifo_generator_status/fifo_generator_status.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_status/fifo_generator_status/fifo_generator_status_clocks.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_status/fifo_generator_status.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/inverter_0/inverter_0.xci
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/inverter_0/inverter_0.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_1_9/fifo_generator_1_9.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_1_9/fifo_generator_1_9/fifo_generator_1_9.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_1_9/fifo_generator_1_9/fifo_generator_1_9_clocks.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/fifo_generator_1_9/fifo_generator_1_9.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/nf_10g_interface_ip/nf_10g_interface_ip.xci
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/nf_10g_interface_ip/nf_10g_interface_ip.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/axi_10g_ethernet_shared.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/bd_0/ip/ip_0/synth/bd_a1aa_xmac_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/bd_0/ip/ip_0/synth/bd_a1aa_xmac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/synth/bd_a1aa_xpcs_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/synth/bd_a1aa_xpcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/synth/bd_a1aa_xpcs_0.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/bd_0/bd_a1aa_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/synth/axi_10g_ethernet_shared_ooc.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/axi_10g_ethernet_shared/axi_10g_ethernet_shared.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/nf_10g_interface_shared_ip/nf_10g_interface_shared_ip.xci
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/nf_10g_interface_shared_ip/nf_10g_interface_shared_ip.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/clk_wiz_ip/clk_wiz_ip.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/clk_wiz_ip/clk_wiz_ip_board.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/clk_wiz_ip/clk_wiz_ip.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/clk_wiz_ip/clk_wiz_ip_late.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/clk_wiz_ip/clk_wiz_ip_ooc.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/clk_wiz_ip/clk_wiz_ip.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/proc_sys_reset_ip/proc_sys_reset_ip.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/proc_sys_reset_ip/proc_sys_reset_ip_board.xdc]
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/proc_sys_reset_ip/proc_sys_reset_ip.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/proc_sys_reset_ip/proc_sys_reset_ip.xci]

read_ip -quiet /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/identifier_ip/identifier_ip.xci
set_property used_in_implementation false [get_files -all /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/identifier_ip/identifier_ip_ooc.xdc]
set_property is_locked true [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/identifier_ip/identifier_ip.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zhs/NetFPGA-SUME-live-master/lib/hw/std/constraints/generic_bit.xdc
set_property used_in_implementation false [get_files /home/zhs/NetFPGA-SUME-live-master/lib/hw/std/constraints/generic_bit.xdc]

read_xdc /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_general.xdc
set_property used_in_implementation false [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_general.xdc]

read_xdc /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_10g.xdc
set_property used_in_implementation false [get_files /home/zhs/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_10g.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7vx690tffg1761-3


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
