# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
create_project -in_memory -part xc7vx690tffg1761-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.cache/wt [current_project]
set_property parent.project_path /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/ip_repo [current_project]
read_ip /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/output_port_lookup_ip/output_port_lookup_ip.xci
set_property is_locked true [get_files /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/project/reference_switch.srcs/sources_1/ip/output_port_lookup_ip/output_port_lookup_ip.xci]

read_xdc /home/maskerk/NetFPGA-SUME-live-master/lib/hw/std/constraints/generic_bit.xdc
set_property used_in_implementation false [get_files /home/maskerk/NetFPGA-SUME-live-master/lib/hw/std/constraints/generic_bit.xdc]

read_xdc /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_general.xdc
set_property used_in_implementation false [get_files /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_general.xdc]

read_xdc /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_10g.xdc
set_property used_in_implementation false [get_files /home/maskerk/NetFPGA-SUME-live-master/projects/reference_switch/hw/constraints/nf_sume_10g.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7vx690tffg1761-3
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
